# Generated by Django 3.0.6 on 2020-06-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('На рассмотрении', 'На рассмотрении'), ('Уже выполнено', 'Уже выполнено')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Есть в наличии', 'Есть в наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=200, null=True),
        ),
    ]
