# Generated by Django 3.0.6 on 2020-06-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200622_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='note',
            new_name='tag',
        ),
    ]
